spring:
#  profiles:
#    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库访问配置
    driver-class-name: com.mysql.jdbc.Driver
    name: mysql
    url: jdbc:mysql://localhost:3306/datacollectionsystem?autoReconnect=true&useSSL=false
    username: jess
    password: 123456
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      filter:
        stat:
          log-slow-sql: true
  data:
    mongodb:
      uri: mongodb://39.105.9.158:27017/spider
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  path: D:\\
  file: datacollectionsystem.log

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.datacollector.model

mapper:
  mappers: org.datacollector.util.BaseMapper
  not-empty: true
  identity: MYSQL


pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
    offset-as-page-num: true











